const currency = new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0});
const iconMap = {rice:'◌',pizza:'△',burger:'☰',wrap:'▱',chicken:'♧',soup:'♨',suya:'◈',drink:'▥',dessert:'▰'};
const categories = [['Jollof Rice','rice'],['Pizza','pizza'],['Burgers','burger'],['Shawarma','wrap'],['Chicken','chicken'],['Soups','soup'],['Suya','suya'],['Drinks','drink'],['Desserts','dessert']];
const stores = [
{id:1,name:'Shawarma Palace',cuisine:'Lebanese · Fast Food',rating:4.7,eta:25,fee:300,icon:'wrap',badge:'New',open:true,favorite:false,freeDelivery:false,promos:true},
{id:2,name:'The Pot Kitchen',cuisine:'Nigerian · West African',rating:4.8,eta:20,fee:350,icon:'soup',badge:'10% off',open:true,favorite:false,freeDelivery:false,promos:true},
{id:3,name:'Burger Lab',cuisine:'Burgers · Grills',rating:4.3,eta:18,fee:400,icon:'burger',badge:'',open:false,favorite:true,freeDelivery:false,promos:false},
{id:4,name:'GreenBowl',cuisine:'Healthy · Salads',rating:4.6,eta:40,fee:250,icon:'soup',badge:'',open:true,favorite:false,freeDelivery:false,promos:false},
{id:5,name:'Slice Bros',cuisine:'Pizza · Fast Food',rating:4.5,eta:25,fee:500,icon:'pizza',badge:'',open:true,favorite:false,freeDelivery:false,promos:false},
{id:6,name:'Suya Republic',cuisine:'BBQ · Nigerian',rating:4.9,eta:15,fee:0,icon:'suya',badge:'Free delivery',open:true,favorite:false,freeDelivery:true,promos:false},
{id:7,name:'Mama Kemi Snacks',cuisine:'Nigerian · Snacks',rating:4.6,eta:15,fee:150,icon:'dessert',badge:'',open:true,favorite:false,freeDelivery:false,promos:false},
{id:8,name:'Lagos Smokehouse',cuisine:'BBQ · Grills',rating:4.9,eta:25,fee:550,icon:'chicken',badge:'Weekend deal',open:true,favorite:false,freeDelivery:false,promos:true},
{id:9,name:'Noodle Republic',cuisine:'Asian · Fast Food',rating:4.6,eta:20,fee:300,icon:'soup',badge:'',open:true,favorite:false,freeDelivery:false,promos:false}
];
const products = [{name:'Jollof Rice & Chicken',restaurant:'The Pot Kitchen',price:2500,icon:'rice'},{name:'Pepperoni Pizza',restaurant:'Slice Bros',price:4200,icon:'pizza'},{name:'Double Smash Burger',restaurant:'Burger Lab',price:3800,icon:'burger'},{name:'Beef Suya (300g)',restaurant:'Suya Republic',price:2200,icon:'suya'}];
const notifications = [{icon:'✓',title:'Your order from The Pot Kitchen was delivered!',time:'2 min ago',unread:true},{icon:'!',title:'50% off on all pizzas this weekend. Use code PIZZA50.',time:'1 hr ago',unread:true},{icon:'☆',title:'How was your last order? Rate The Pot Kitchen.',time:'3 hrs ago',unread:true},{icon:'i',title:'New restaurant added near you: Lagos Smokehouse.',time:'Yesterday',unread:false},{icon:'₦',title:'Top up NGN 5,000 or more and get NGN 500 cashback!',time:'2 days ago',unread:false}];
const filters = [{id:'open',label:'Open now',predicate:s=>s.open},{id:'freeDelivery',label:'Free delivery',predicate:s=>s.freeDelivery},{id:'fast',label:'Under 20 min',predicate:s=>s.eta<=20},{id:'top',label:'Top rated',predicate:s=>s.rating>=4.8},{id:'promos',label:'Promos',predicate:s=>s.promos},{id:'new',label:'New',predicate:s=>s.badge.toLowerCase()==='new'}];
const state = {isLoadingStores:true,activeFilters:new Set(),sort:'relevance',query:''};
const $ = selector => document.querySelector(selector); const foodIcon = name => '<span class="food-icon" aria-hidden="true">'+(iconMap[name] || '□')+'</span>'; const money = amount => amount === 0 ? 'Free' : currency.format(amount);
function renderActiveOrder(){const steps=['Placed','Confirmed','Preparing','On the way','Delivered']; $('#active-order').innerHTML='<article class="active-order" aria-labelledby="active-order-title"><div class="active-order-top"><div><p class="kicker">Active order</p><h2 id="active-order-title">2x Jollof Rice + Chicken</h2><p class="muted">The Pot Kitchen</p></div><span class="eta">9 min</span></div><ol class="progress" aria-label="Order progress">'+steps.map((step,i)=>'<li class="'+(i<2?'done':i===2?'current':'')+'">'+step+'</li>').join('')+'</ol></article>';}
function renderCategories(){ $('#categories').innerHTML = categories.map(c=>'<button class="category-card" type="button">'+foodIcon(c[1])+'<span>'+c[0]+'</span></button>').join(''); }
function renderStoreCard(s){return '<article class="store-card" aria-label="'+s.name+'">'+(s.badge?'<span class="badge">'+s.badge+'</span>':'')+'<button class="icon-button" type="button" aria-label="'+(s.favorite?'Remove ':'Save ')+s.name+'" aria-pressed="'+s.favorite+'">♡</button><div class="media '+(!s.open?'dark':'')+'">'+foodIcon(s.icon)+'</div>'+(!s.open?'<span class="closed-pill">Closed now</span>':'')+'<div class="card-body"><h3 title="'+s.name+'">'+s.name+'</h3><p class="muted">'+s.cuisine+'</p><div class="meta-row"><span class="rating">★ '+s.rating.toFixed(1)+'</span><span>'+s.eta+'-'+(s.eta+10)+' min</span><span>'+money(s.fee)+'</span></div></div></article>';}
function renderProductCard(p){return '<article class="product-card"><div class="media">'+foodIcon(p.icon)+'</div><div class="card-body"><h3 title="'+p.name+'">'+p.name+'</h3><p class="muted">'+p.restaurant+'</p><div class="price-row"><strong>'+money(p.price)+'</strong><button class="add-button" type="button" aria-label="Add '+p.name+'">+</button></div></div></article>';}
function renderFeatured(){ $('#featured').innerHTML = stores.slice(0,4).map(renderStoreCard).join(''); } function renderRecommended(){ $('#recommended').innerHTML = products.map(renderProductCard).join(''); }
function renderReorder(){ $('#reorder').innerHTML = products.slice(0,3).map((item,i)=>'<article class="order-again"><span class="thumb">'+(iconMap[item.icon] || '□')+'</span><div><h3>'+(i===0?'2x ':'')+item.name+'</h3><p class="muted">'+item.restaurant+' · '+(i===0?'Yesterday':(i+2)+' days ago')+'</p></div><button class="button soft" type="button">Reorder</button></article>').join(''); }
function renderWallet(){ $('#wallet').innerHTML='<section class="wallet" aria-labelledby="wallet-title"><h2 id="wallet-title">Wallet balance</h2><p class="balance">₦4,250<span aria-hidden="true">.00</span></p><div class="wallet-actions"><button class="button" type="button">Add funds</button><button class="button secondary" type="button">History</button></div><div class="transaction-list" aria-label="Recent wallet activity"><div class="transaction"><span>Order #4821 debit</span><strong>-₦2,500</strong></div><div class="transaction"><span>Wallet top-up</span><strong>+₦5,000</strong></div><div class="transaction"><span>Order #4801 debit</span><strong>-₦3,800</strong></div></div></section>'; }
function renderNotifications(){ $('#notifications').innerHTML = notifications.map(n=>'<article class="notification '+(n.unread?'unread':'')+'"><span class="notification-icon" aria-hidden="true">'+n.icon+'</span><div><h3>'+n.title+'</h3><p class="muted">'+n.time+'</p></div><span class="'+(n.unread?'unread-dot':'')+'" aria-label="'+(n.unread?'Unread':'')+'"></span></article>').join(''); }
function renderFilters(){ $('#filters').innerHTML = filters.map(f=>'<button class="chip" type="button" data-filter="'+f.id+'" aria-pressed="'+state.activeFilters.has(f.id)+'"><span class="chip-dot" aria-hidden="true"></span>'+f.label+'</button>').join(''); }
function visibleStores(){ let v=[...stores]; if(state.query){ const q=state.query.toLowerCase(); v=v.filter(s=>(s.name+' '+s.cuisine).toLowerCase().includes(q)); } for(const id of state.activeFilters){ const f=filters.find(x=>x.id===id); v=v.filter(f.predicate); } if(state.sort==='rating') v.sort((a,b)=>b.rating-a.rating); if(state.sort==='eta') v.sort((a,b)=>a.eta-b.eta); return v; }
function renderSkeletons(){ $('#stores').innerHTML = Array.from({length:6},()=>'<article class="skeleton" aria-label="Loading store"><div></div><p></p><p style="width:58%"></p></article>').join(''); }
function renderEmpty(){ $('#stores').innerHTML='<div class="empty-state">'+foodIcon('dessert')+'<h3>No stores match this view</h3><p class="muted">Try a different search, remove a filter, or sort by relevance.</p></div>'; }
function renderStores(){ if(state.isLoadingStores){ renderSkeletons(); return; } const v=visibleStores(); $('#store-count').textContent=v.length; $('#stores').innerHTML = v.length ? v.map(renderStoreCard).join('') : ''; if(!v.length) renderEmpty(); }
function bindEvents(){ $('#filters').addEventListener('click',e=>{ const b=e.target.closest('[data-filter]'); if(!b)return; const id=b.dataset.filter; state.activeFilters.has(id)?state.activeFilters.delete(id):state.activeFilters.add(id); renderFilters(); renderStores(); }); $('#sort-select').addEventListener('change',e=>{ state.sort=e.target.value; renderStores(); }); $('.search').addEventListener('submit',e=>{ e.preventDefault(); state.query=$('#global-search').value.trim(); renderStores(); }); $('#global-search').addEventListener('input',e=>{ state.query=e.target.value.trim(); renderStores(); }); }
function renderApp(){ renderActiveOrder(); renderCategories(); renderFeatured(); renderRecommended(); renderReorder(); renderWallet(); renderNotifications(); renderFilters(); renderStores(); bindEvents(); window.setTimeout(()=>{state.isLoadingStores=false; renderStores();},500); }
renderApp();